on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  check-coverage:
    runs-on: ubuntu-latest
    name: Check coverage
    steps:
      - uses: actions/checkout@v1
      - name:
        id: hello
        uses: ./
        with:
          clover_file: "coverage/clover.xml"
          original_clover_file: "original_clover.xml"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          S3_ACCESS_KEY: ${{secrets.S3_ACCESS_KEY}}
          S3_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}
          S3_BUCKET: ${{secrets.S3_BUCKET}}
          S3_REGION: ${{secrets.S3_REGION}}
