on:
  push:
    branches:
      - master
jobs:
  write-coverage:
    runs-on: ubuntu-latest
    name: Check coverage
    steps:
      - uses: actions/checkout@v1
      - run: |
          cp -f coverage/clover.xml original_clover.xml
          git commit -m 'Update coverage file' original_clover.xml
          git push
