on:
  push:
    branches:
      - master
jobs:
  write-coverage:
    runs-on: ubuntu-latest
    name: Check coverage
    steps:
      - uses: actions/checkout@v1
      - name:
        id: main-merge
        uses: ./
        with:
          clover_file: "coverage/clover.xml"
          original_clover_file: "original_clover.xml"
          update_coverage: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          S3_ACCESS_KEY: ${{secrets.S3_ACCESS_KEY}}
          S3_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}
          S3_BUCKET: ${{secrets.S3_BUCKET}}
          S3_REGION: ${{secrets.S3_REGION}}
